### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by vpontin** [modmuss50/StructureUtils#1]
Hi! Frist of all thanks for this mod!

I want to know if this mod can break [Pillar](https://github.com/Vazkii/Pillar), a mod made by Vazkii which uses [the structure system to spawn ruins](https://minecraft.curseforge.com/projects/pillar) (similar to how Ruins mod did).

My question is: can i use both mods together? I'm very interested on the block fix but i'm afraid it can interfere in any way in pillar and its structure spawning system.

Thanks in advance!

**Comment by modmuss50** [comment]
It should be compatible as long as it does not use a core mod to change the same things my mod does.

I would create a backup or a new world to test it in first as my mod hasn’t had a geat deal of testing. If there is some incompabilty I could look into fixing it.

**Comment by vpontin** [comment]
Okay, thanks for the help!
